# Generated by Django 4.0.4 on 2022-05-02 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('detail', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('detail', models.CharField(blank=True, max_length=250, null=True, verbose_name='Detalle')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('stock', models.FloatField(verbose_name='Cantidad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tienda/categorias')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendaApp.category')),
            ],
        ),
    ]
